group:
  - files:
    - source: content/Plugin.md
      dest: README.md
    repos: |
      ObsidianPublisher/obsidian-github-publisher
  - files:
    - source: content/wikis/Quartz.md
      dest: README.md
    repos: |
      ObsidianPublisher/Publisher-Quartz
