group:
  - files:
    - docs/assets/css/custom_attributes.css
    - docs/assets/css/customization.css
    - source: docs/Template/configuration.md
      dest: README.md
    repos: |
      ObsidianPublisher/mkdocs-template
  - files:
    - source: docs/Plugin/index.md
      dest: README.md
    repos: |
      ObsidianPublisher/obsidian-github-publisher
  - files:
    - source: docs/Template/Actions.md
      dest: README.md
    repos: |
      ObsidianPublisher/actions

