name: Repository maintenance

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
      - uses: ObsidianPublisher/actions/maintenance@main