name: Repository maintenance
description: 'This workflow is triggered daily to clean unused images and update requirements'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
      - uses: ObsidianPublisher/actions/maintenance@main