name: Repository maintenance

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ObsidianPublisher/actions/.github/workflows/maintenance.yml@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}